services:

  chose:
    image: shoes:1.0
    container_name: chose_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db


  db:
    image: postgres:16.3
    container_name: shoes_db
    restart: always
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]

volumes:
  dev_pg_data:
    driver: local