spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html

  datasource:
    username: misha
    password: fullmetal
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5436/shoes
  application:
    name: shoes

server:
  port: 8085